apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cassata.clusterRoleBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cassata.serviceAccount.name }}
    namespace: {{ .Values.cassata.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.cassata.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
