apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.cassata.clusterRole.name }}
spec:
  rules:
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - clusterroles
      verbs:
        - update
        - get
        - list
