apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cassata.fullname" . }}
  namespace: {{ .Values.cassata.namespace }}
spec:
  replicas: {{ .Values.cassata.replicaCount }}
  selector:
    matchLabels:
{{- include "cassata.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "cassata.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.cassata.serviceAccount.name }}
      initContainers:
        - name: init-cassata
          image: {{ .Values.cassata.image.name }}
          command: ["/cassata-init"]
          env:
            - name: NAMESPACE
              value: "{{ .Values.cassata.namespace }}"
            - name: JWT_SECRET_NAME
              value: "{{ .Values.cassata.jwtSecret.name }}"
            - name: DATABASE_SECRET_NAME
              value: "{{ .Values.database.secret.name }}"
            - name: DATABASE_EXTERNAL
              value: "{{ .Values.database.external }}"
            - name: DATABASE_DSN
              value: "{{ .Values.database.dsn }}"
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.cassata.image.name }}
          imagePullPolicy: {{ .Values.cassata.image.pullPolicy }}
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cassata.jwtSecret.name }}
                  key: JWT_SECRET_KEY
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: DATABASE_DSN
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
