{{- if and .Values.database.external }}
apiVersion: v1
kind: Service
metadata:
  name: cassata-postgres
  namespace: {{ .Values.cassata.namespace }}
  labels:
    {{- include "cassata.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 5432
  selector:
    {{- include "cassata.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}