apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassata.fullname" . }}
  namespace: {{ .Values.cassata.namespace }}
  labels:
    {{- include "cassata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cassata.service.type }}
  ports:
    - port: {{ .Values.cassata.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cassata.selectorLabels" . | nindent 4 }}