apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: 
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET_KEY