cassata:
  image:
    name: bharathk005/cassata:latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  initContainer:
    image: bharathk005/cassata-init:latest

  service:
    type: ClusterIP
    port: 80

  jwtSecret:
    name: cassata-jwt-secret

  serviceAccount:
    name: cassata-service-account

  clusterRole:
    name: cassata-cluster-role

  clusterRoleBinding:
    name: cassata-cluster-role-binding

database:
  external: true
  dsn: "" # Data Source Name for the external database. Required when external is true.

postgres:
  image:
    repository: postgres
    tag: 13
  persistence:
    enabled: true
    size: 1Gi